on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Typical Usage of OpenVPN
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install OpenVPN
        run: sudo apt install -y openvpn openvpn-systemd-resolved
      - name: Connect to VPN
        uses: "./"
        with:
          config_file: .github/workflows/client.ovpn
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}
      - name: Check if connected
        uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            password: ${{ secrets.SSH_PASSWORD }}
            port: 22
            script: "./updatejetty.sh"
